### ISSUE TITLE
Add Discord and TikTok Link to footer

### ISSUE THREAD

**Issue by wizzdom** [redbrick/atlas#28]
It would be pretty cool 👀

**Comment by MadRedStone** [comment]
lemme do it pls :3

**Comment by novanai** [comment]
You can also update the twitter icon to the new X, if you need the svg take it from [this PR](https://github.com/redbrick/atlas/pull/32/files#diff-535c004be2eafa0bcdc556f1c146a7441ab0ee2ce0b5dc78fe934e16e4b0045fR52-R58)
