### ISSUE TITLE
Blog nav link needs updating

### ISSUE THREAD

**Issue by novanai** [redbrick/atlas#29]
The Blog link in the navigation bar currently points to <https://redbrick.dcu.ie/blog/posts/2024-01-31-redbrick-maintenance-with-nomad.html> while it should instead point to <https://redbrick.dcu.ie/blog/readme.html>

**Comment by hafizakbar19** [comment]
Hello novanai,
can you assign it to me?

**Comment by novanai** [comment]
@MadRedStone has requested to work on this issue.

**Comment by novanai** [comment]
Fixed by #31
